In [1]:
import matplotlib.pyplot as plt
import solvers
import numpy as np

In [2]:
# examples
a = 0
b = 2
T = 1

# k = lambda u, x, t: u**1
q = lambda u, x, t: 1

f = lambda u, x, t: 0

# mu_a = lambda t: 1*t**(-0.2)#1*t**(-0.2)
mu_a = lambda K: [lambda t: 0, lambda t: 1, lambda t: 1*t**(K)]#1*t**(-0.2)]
mu_b = [lambda t: 0, lambda t: 1, lambda t: 0]

u0 = lambda x: 0

tau = 0.01
h = 0.01

In [ ]:
fig, axs = plt.subplots(3, 2)
fig.set_figheight(15)
fig.set_figwidth(15)

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**1, f, u0, mu_a(0), mu_b, a, b, T, h, tau)
axs[0, 0].plot(Xs, U[20], color="green")
axs[0, 0].plot(Xs, U[40], color="yellow")
axs[0, 0].plot(Xs, U[60], color="orange")
axs[0, 0].plot(Xs, U[80], color="red")
axs[0, 0].plot(Xs, U[-1], color="blue")
axs[0, 0].set_title('n=1, k=0')
axs[0, 0].set_xlabel('X')
axs[0, 0].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**2, f, u0, mu_a(0), mu_b, a, b, T, h, tau)
axs[0, 1].plot(Xs, U[20], color="green")
axs[0, 1].plot(Xs, U[40], color="yellow")
axs[0, 1].plot(Xs, U[60], color="orange")
axs[0, 1].plot(Xs, U[80], color="red")
axs[0, 1].plot(Xs, U[-1], color="blue")
axs[0, 1].set_title('n=2, k=0')
axs[0, 1].set_xlabel('X')
axs[0, 1].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**1, f, u0, mu_a(1), mu_b, a, b, T, h, tau)
axs[1, 0].plot(Xs, U[20], color="green")
axs[1, 0].plot(Xs, U[40], color="yellow")
axs[1, 0].plot(Xs, U[60], color="orange")
axs[1, 0].plot(Xs, U[80], color="red")
axs[1, 0].plot(Xs, U[-1], color="blue")
axs[1, 0].set_title('n=1, k=1')
axs[1, 0].set_xlabel('X')
axs[1, 0].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**2, f, u0, mu_a(1/2), mu_b, a, b, T, h, tau)
axs[1, 1].plot(Xs, U[20], color="green")
axs[1, 1].plot(Xs, U[40], color="yellow")
axs[1, 1].plot(Xs, U[60], color="orange")
axs[1, 1].plot(Xs, U[80], color="red")
axs[1, 1].plot(Xs, U[-1], color="blue")
axs[1, 1].set_title('n=2, k=1/2')
axs[1, 1].set_xlabel('X')
axs[1, 1].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**3, f, u0, mu_a(1), mu_b, a, b, T, h, tau)
axs[2, 0].plot(Xs, U[20], color="green")
axs[2, 0].plot(Xs, U[40], color="yellow")
axs[2, 0].plot(Xs, U[60], color="orange")
axs[2, 0].plot(Xs, U[80], color="red")
axs[2, 0].plot(Xs, U[-1], color="blue")
axs[2, 0].set_title('n=3, k=1')
axs[2, 0].set_xlabel('X')
axs[2, 0].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**1, f, u0, mu_a(-0.2), mu_b, a, b, T, h, tau)
axs[2, 1].plot(Xs, U[20], color="green")
axs[2, 1].plot(Xs, U[40], color="yellow")
axs[2, 1].plot(Xs, U[60], color="orange")
axs[2, 1].plot(Xs, U[80], color="red")
axs[2, 1].plot(Xs, U[-1], color="blue")
axs[2, 1].set_title('n=1, k=-0.2')
axs[2, 1].set_xlabel('X')
axs[2, 1].set_ylabel('U')

plt.show()

In [ ]:
# legacy examples
mu_a = lambda t: 1*t**(-0.2)#1*t**(-0.2)
mu_b = lambda t: 0

fig, axs = plt.subplots(3, 2)
fig.set_figheight(15)
fig.set_figwidth(15)

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**1, f, u0,lambda t: 1*t**(0), mu_b, a, b, T, h, tau)
axs[0, 0].plot(Xs, U[20], color="green")
axs[0, 0].plot(Xs, U[40], color="yellow")
axs[0, 0].plot(Xs, U[60], color="orange")
axs[0, 0].plot(Xs, U[80], color="red")
axs[0, 0].plot(Xs, U[-1], color="blue")
axs[0, 0].set_title('n=1, k=0')
axs[0, 0].set_xlabel('X')
axs[0, 0].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**2, f, u0,lambda t: 1*t**(0), mu_b, a, b, T, h, tau)
axs[0, 1].plot(Xs, U[20], color="green")
axs[0, 1].plot(Xs, U[40], color="yellow")
axs[0, 1].plot(Xs, U[60], color="orange")
axs[0, 1].plot(Xs, U[80], color="red")
axs[0, 1].plot(Xs, U[-1], color="blue")
axs[0, 1].set_title('n=2, k=0')
axs[0, 1].set_xlabel('X')
axs[0, 1].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**1, f, u0,lambda t: 1*t**(1), mu_b, a, b, T, h, tau)
axs[1, 0].plot(Xs, U[20], color="green")
axs[1, 0].plot(Xs, U[40], color="yellow")
axs[1, 0].plot(Xs, U[60], color="orange")
axs[1, 0].plot(Xs, U[80], color="red")
axs[1, 0].plot(Xs, U[-1], color="blue")
axs[1, 0].set_title('n=1, k=1')
axs[1, 0].set_xlabel('X')
axs[1, 0].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**2, f, u0,lambda t: 1*t**(1/2), mu_b, a, b, T, h, tau)
axs[1, 1].plot(Xs, U[20], color="green")
axs[1, 1].plot(Xs, U[40], color="yellow")
axs[1, 1].plot(Xs, U[60], color="orange")
axs[1, 1].plot(Xs, U[80], color="red")
axs[1, 1].plot(Xs, U[-1], color="blue")
axs[1, 1].set_title('n=2, k=1/2')
axs[1, 1].set_xlabel('X')
axs[1, 1].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**3, f, u0,lambda t: 1*t**(1), mu_b, a, b, T, h, tau)
axs[2, 0].plot(Xs, U[20], color="green")
axs[2, 0].plot(Xs, U[40], color="yellow")
axs[2, 0].plot(Xs, U[60], color="orange")
axs[2, 0].plot(Xs, U[80], color="red")
axs[2, 0].plot(Xs, U[-1], color="blue")
axs[2, 0].set_title('n=3, k=1')
axs[2, 0].set_xlabel('X')
axs[2, 0].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**1, f, u0,lambda t: 1*t**(-0.2), mu_b, a, b, T, h, tau)
axs[2, 1].plot(Xs, U[20], color="green")
axs[2, 1].plot(Xs, U[40], color="yellow")
axs[2, 1].plot(Xs, U[60], color="orange")
axs[2, 1].plot(Xs, U[80], color="red")
axs[2, 1].plot(Xs, U[-1], color="blue")
axs[2, 1].set_title('n=1, k=-0.2')
axs[2, 1].set_xlabel('X')
axs[2, 1].set_ylabel('U')

plt.show()

In [12]:
#Numerical method for solving the system of linear equations
#Seidel method

def Seidel(A, b, eps):
    x = x_new = np.zeros(len(A))
    while True:
        x_new = x + (b - np.dot(A, x)) / np.diag(A)
        if np.linalg.norm(x_new - x) < eps:
            break
        x = x_new.copy()
    return x

#Example
#Generate a random symmetric matrix A
A = np.random.rand(5, 5)
A = np.dot(A, A.T) + np.eye(5) * 1
print(A)
#Generate a random vector b
b = np.random.rand(5)
#Check matrix compatibility
if np.linalg.det(A) == 0:
    print("System isn't compatible")
else:
    #Machine precision
    eps = np.finfo(float).eps
    print("Solution, using Seidel method: ", Seidel(A, b, eps))
    #Compare with the result of the numpy.linalg.solve function
    print("Solution, using numpy.linalg.solve: ", np.linalg.solve(A, b))

[[2.32171578 1.0699932  1.16296702 1.45018439 1.12688734]
 [1.0699932  2.75996628 1.25548915 1.82701742 1.35515321]
 [1.16296702 1.25548915 2.7326752  1.82533951 1.55670647]
 [1.45018439 1.82701742 1.82533951 3.27211825 1.69916945]
 [1.12688734 1.35515321 1.55670647 1.69916945 2.80874172]]


C:\Users\stas2\AppData\Local\Temp\ipykernel_19116\404233091.py:7: RuntimeWarning: invalid value encountered in add
  x_new = x + (b - np.dot(A, x)) / np.diag(A)


KeyboardInterrupt: 

In [15]:
#Функция нахождения нормы Фробениуса матрицы
def NormF(A):
    return pow(sum(abs(A[i][j])**2 for i in range(len(A)) for j in range(len(A))), 1/2)

#Нахождение обратной матрицы методом Гаусса
def InverseMatrix(A):
    #Создание единичной матрицы
    E = np.eye(len(A))
    #Создание расширенной матрицы
    A = np.concatenate((A, E), axis=1)
    #Прямой ход
    for i in range(len(A)):
        #Нахождение максимального элемента в столбце
        max_el = abs(A[i][i])
        max_row = i
        for k in range(i + 1, len(A)):
            if abs(A[k][i]) > max_el:
                max_el = abs(A[k][i])
                max_row = k
        #Поменять местами строку с максимальным элементом и текущую
        for k in range(len(A[i])):
            A[max_row][k], A[i][k] = A[i][k], A[max_row][k]
        #Деление строки на максимальный элемент
        for k in range(len(A[i])):
            A[i][k] = A[i][k] / max_el
        #Вычитание строк
        for k in range(len(A)):
            if k != i:
                c = A[k][i] / A[i][i]
                for j in range(len(A[i])):
                    A[k][j] = A[k][j] - c * A[i][j]
    #Создание обратной матрицы
    A = A[:, len(A):]
    return A

#Функция нахождения числа обусловленности матрицы
def ConditionNumber(A, Norm):
    return Norm(A) * Norm(InverseMatrix(A))

print(ConditionNumber(A, NormF))
print(np.linalg.cond(A))

27.00704982401248
22.127758438716018
