In [1]:
import matplotlib.pyplot as plt
import solvers
import numpy as np

In [2]:
# examples
a = 0
b = 2
T = 1

# k = lambda u, x, t: u**1
q = lambda u, x, t: 1

f = lambda u, x, t: 0

# mu_a = lambda t: 1*t**(-0.2)#1*t**(-0.2)
mu_a = lambda K: [lambda t: 0, lambda t: 1, lambda t: 1*t**(K)]#1*t**(-0.2)]
mu_b = [lambda t: 0, lambda t: 1, lambda t: 0]

u0 = lambda x: 0

tau = 0.01
h = 0.01

In [ ]:
fig, axs = plt.subplots(3, 2)
fig.set_figheight(15)
fig.set_figwidth(15)

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**1, f, u0, mu_a(0), mu_b, a, b, T, h, tau)
axs[0, 0].plot(Xs, U[20], color="green")
axs[0, 0].plot(Xs, U[40], color="yellow")
axs[0, 0].plot(Xs, U[60], color="orange")
axs[0, 0].plot(Xs, U[80], color="red")
axs[0, 0].plot(Xs, U[-1], color="blue")
axs[0, 0].set_title('n=1, k=0')
axs[0, 0].set_xlabel('X')
axs[0, 0].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**2, f, u0, mu_a(0), mu_b, a, b, T, h, tau)
axs[0, 1].plot(Xs, U[20], color="green")
axs[0, 1].plot(Xs, U[40], color="yellow")
axs[0, 1].plot(Xs, U[60], color="orange")
axs[0, 1].plot(Xs, U[80], color="red")
axs[0, 1].plot(Xs, U[-1], color="blue")
axs[0, 1].set_title('n=2, k=0')
axs[0, 1].set_xlabel('X')
axs[0, 1].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**1, f, u0, mu_a(1), mu_b, a, b, T, h, tau)
axs[1, 0].plot(Xs, U[20], color="green")
axs[1, 0].plot(Xs, U[40], color="yellow")
axs[1, 0].plot(Xs, U[60], color="orange")
axs[1, 0].plot(Xs, U[80], color="red")
axs[1, 0].plot(Xs, U[-1], color="blue")
axs[1, 0].set_title('n=1, k=1')
axs[1, 0].set_xlabel('X')
axs[1, 0].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**2, f, u0, mu_a(1/2), mu_b, a, b, T, h, tau)
axs[1, 1].plot(Xs, U[20], color="green")
axs[1, 1].plot(Xs, U[40], color="yellow")
axs[1, 1].plot(Xs, U[60], color="orange")
axs[1, 1].plot(Xs, U[80], color="red")
axs[1, 1].plot(Xs, U[-1], color="blue")
axs[1, 1].set_title('n=2, k=1/2')
axs[1, 1].set_xlabel('X')
axs[1, 1].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**3, f, u0, mu_a(1), mu_b, a, b, T, h, tau)
axs[2, 0].plot(Xs, U[20], color="green")
axs[2, 0].plot(Xs, U[40], color="yellow")
axs[2, 0].plot(Xs, U[60], color="orange")
axs[2, 0].plot(Xs, U[80], color="red")
axs[2, 0].plot(Xs, U[-1], color="blue")
axs[2, 0].set_title('n=3, k=1')
axs[2, 0].set_xlabel('X')
axs[2, 0].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**1, f, u0, mu_a(-0.2), mu_b, a, b, T, h, tau)
axs[2, 1].plot(Xs, U[20], color="green")
axs[2, 1].plot(Xs, U[40], color="yellow")
axs[2, 1].plot(Xs, U[60], color="orange")
axs[2, 1].plot(Xs, U[80], color="red")
axs[2, 1].plot(Xs, U[-1], color="blue")
axs[2, 1].set_title('n=1, k=-0.2')
axs[2, 1].set_xlabel('X')
axs[2, 1].set_ylabel('U')

plt.show()

In [ ]:
# legacy examples
mu_a = lambda t: 1*t**(-0.2)#1*t**(-0.2)
mu_b = lambda t: 0

fig, axs = plt.subplots(3, 2)
fig.set_figheight(15)
fig.set_figwidth(15)

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**1, f, u0,lambda t: 1*t**(0), mu_b, a, b, T, h, tau)
axs[0, 0].plot(Xs, U[20], color="green")
axs[0, 0].plot(Xs, U[40], color="yellow")
axs[0, 0].plot(Xs, U[60], color="orange")
axs[0, 0].plot(Xs, U[80], color="red")
axs[0, 0].plot(Xs, U[-1], color="blue")
axs[0, 0].set_title('n=1, k=0')
axs[0, 0].set_xlabel('X')
axs[0, 0].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**2, f, u0,lambda t: 1*t**(0), mu_b, a, b, T, h, tau)
axs[0, 1].plot(Xs, U[20], color="green")
axs[0, 1].plot(Xs, U[40], color="yellow")
axs[0, 1].plot(Xs, U[60], color="orange")
axs[0, 1].plot(Xs, U[80], color="red")
axs[0, 1].plot(Xs, U[-1], color="blue")
axs[0, 1].set_title('n=2, k=0')
axs[0, 1].set_xlabel('X')
axs[0, 1].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**1, f, u0,lambda t: 1*t**(1), mu_b, a, b, T, h, tau)
axs[1, 0].plot(Xs, U[20], color="green")
axs[1, 0].plot(Xs, U[40], color="yellow")
axs[1, 0].plot(Xs, U[60], color="orange")
axs[1, 0].plot(Xs, U[80], color="red")
axs[1, 0].plot(Xs, U[-1], color="blue")
axs[1, 0].set_title('n=1, k=1')
axs[1, 0].set_xlabel('X')
axs[1, 0].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**2, f, u0,lambda t: 1*t**(1/2), mu_b, a, b, T, h, tau)
axs[1, 1].plot(Xs, U[20], color="green")
axs[1, 1].plot(Xs, U[40], color="yellow")
axs[1, 1].plot(Xs, U[60], color="orange")
axs[1, 1].plot(Xs, U[80], color="red")
axs[1, 1].plot(Xs, U[-1], color="blue")
axs[1, 1].set_title('n=2, k=1/2')
axs[1, 1].set_xlabel('X')
axs[1, 1].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**3, f, u0,lambda t: 1*t**(1), mu_b, a, b, T, h, tau)
axs[2, 0].plot(Xs, U[20], color="green")
axs[2, 0].plot(Xs, U[40], color="yellow")
axs[2, 0].plot(Xs, U[60], color="orange")
axs[2, 0].plot(Xs, U[80], color="red")
axs[2, 0].plot(Xs, U[-1], color="blue")
axs[2, 0].set_title('n=3, k=1')
axs[2, 0].set_xlabel('X')
axs[2, 0].set_ylabel('U')

U, Xs, Ts = solvers.ParabolicPartialDifferentialEquation(q, lambda u, x, t: u**1, f, u0,lambda t: 1*t**(-0.2), mu_b, a, b, T, h, tau)
axs[2, 1].plot(Xs, U[20], color="green")
axs[2, 1].plot(Xs, U[40], color="yellow")
axs[2, 1].plot(Xs, U[60], color="orange")
axs[2, 1].plot(Xs, U[80], color="red")
axs[2, 1].plot(Xs, U[-1], color="blue")
axs[2, 1].set_title('n=1, k=-0.2')
axs[2, 1].set_xlabel('X')
axs[2, 1].set_ylabel('U')

plt.show()

In [49]:
import time
#Numerical method for solving the system of linear equations
#Seidel method

def Seidel(A, b, eps):
    x = x_new = np.zeros(len(A))
    D = np.diag(np.diag(A))
    A1 = np.tril(A)
    while True:
        x_new = x + np.dot(np.linalg.inv(A1+D), b - np.dot(A, x))
        if np.linalg.norm(x_new - x) < eps:
            break
        x = x_new.copy()
    return x

#Without matrix operations
def Seidel2(A, b, eps):
    x = np.zeros(len(A))
    x_new = np.zeros(len(A))
    while True:
        for i in range(len(A)):
            x_new[i] = (b[i] - np.sum(A[i][:i] * x_new[:i]) - np.sum(A[i][i+1:] * x[i+1:])) / A[i][i] 
        if np.linalg.norm(x_new - x) < eps:
            break
        x = x_new.copy()
    return x

#Jacobi method
def Jacobi(A, b, eps):
    x = x_new = np.zeros(len(A))
    D = np.diag(np.diag(A))
    A1 = np.tril(A)
    A2 = np.triu(A)
    while True:
        x_new = x + np.dot(np.linalg.inv(D), b - np.dot(A, x))
        if np.linalg.norm(x_new - x) < eps:
            break
        x = x_new.copy()
    return x

#Without matrix operations
def Jacobi2(A, b, eps):
    x = np.zeros(len(A))
    x_new = np.zeros(len(A))
    while True:
        for i in range(len(A)):
            x_new[i] = (b[i] - sum(A[i][j] * x[j] for j in range(len(A)) if i!=j)) / A[i][i] 
        if np.linalg.norm(x_new - x) < eps:
            break
        x = x_new.copy()
    return x

#Example
#Generate a random symmetric matrix A
NN = 1000
A = np.random.rand(NN, NN)
A = np.dot(A, A.T) + np.eye(NN) * NN*NN
# print(A)
#Generate a random vector b
b = np.random.rand(NN)
#Check matrix compatibility
if np.linalg.det(A) == 0:
    print("System isn't compatible")
else:
    #Machine precision
    eps = np.finfo(float).eps
    # perfomance plot
    start = time.time()
    solution = Seidel(A, b, eps)
    work_time = time.time() - start
    solution = 0
    print("Solution, using Seidel method: ", solution, "Time: ", work_time)
    start = time.time()
    solution = Seidel2(A, b, eps)
    work_time = time.time() - start
    solution = 0
    print("Solution, using Seidel2 method: ", solution, "Time: ", work_time)
    
    start = time.time()
    solution = Jacobi(A, b, eps)
    work_time = time.time() - start
    solution = 0
    print("Solution, using Jacobi method: ", solution, "Time: ", work_time)
    
    start = time.time()
    solution = Jacobi2(A, b, eps)
    work_time = time.time() - start
    solution = 0
    print("Solution, using Jacobi2 method: ", solution, "Time: ", work_time)
    
    #Compare with the result of the numpy.linalg.solve function
    start = time.time()
    solution = np.linalg.solve(A, b)
    work_time = time.time() - start
    solution = 0
    print("Solution, using numpy.linalg.solve: ", solution, "Time: ", work_time)

c:\Users\stas2\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\linalg\linalg.py:2146: RuntimeWarning: overflow encountered in det
  r = _umath_linalg.det(a, signature=signature)


Solution, using Seidel method:  0 Time:  2.8825831413269043
Solution, using Seidel2 method:  0 Time:  0.17551922798156738
Solution, using Jacobi method:  0 Time:  1.322948932647705
Solution, using Jacobi2 method:  0 Time:  12.92960810661316
Solution, using numpy.linalg.solve:  0 Time:  0.24244403839111328


In [15]:
4.645965099334717
#Функция нахождения нормы Фробениуса матрицы
def NormF(A):
    return pow(sum(abs(A[i][j])**2 for i in range(len(A)) for j in range(len(A))), 1/2)

#Нахождение обратной матрицы методом Гаусса
def InverseMatrix(A):
    #Создание единичной матрицы
    E = np.eye(len(A))
    #Создание расширенной матрицы
    A = np.concatenate((A, E), axis=1)
    #Прямой ход
    for i in range(len(A)):
        #Нахождение максимального элемента в столбце
        max_el = abs(A[i][i])
        max_row = i
        for k in range(i + 1, len(A)):
            if abs(A[k][i]) > max_el:
                max_el = abs(A[k][i])
                max_row = k
        #Поменять местами строку с максимальным элементом и текущую
        for k in range(len(A[i])):
            A[max_row][k], A[i][k] = A[i][k], A[max_row][k]
        #Деление строки на максимальный элемент
        for k in range(len(A[i])):
            A[i][k] = A[i][k] / max_el
        #Вычитание строк
        for k in range(len(A)):
            if k != i:
                c = A[k][i] / A[i][i]
                for j in range(len(A[i])):
                    A[k][j] = A[k][j] - c * A[i][j]
    #Создание обратной матрицы
    A = A[:, len(A):]
    return A

#Функция нахождения числа обусловленности матрицы
def ConditionNumber(A, Norm):
    return Norm(A) * Norm(InverseMatrix(A))

print(ConditionNumber(A, NormF))
print(np.linalg.cond(A))

27.00704982401248
22.127758438716018


In [33]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.tril(A))

[[1 0 0]
 [4 5 0]
 [7 8 9]]
